apiVersion: v1
kind: Service
metadata:
  name: exam-service
spec:
  selector:
    app: exam-app
  ports:
  - name: web
    port: 8080
    targetPort: 8080
  - name: ssh
    port: 22
    targetPort: 22
  - name: mysql
    port: 3306
    targetPort: 3306